services:
  app:
    container_name: pizzahub-backend-prod
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: bash -c "npm run start:dev"

  nginx:
    image: nginx:alpine
    container_name: pizzahub-nginx
    volumes:
      - ./public:/usr/share/nginx/html
    ports:
      - '5005:80'
